apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tasklify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: Xenor20/tasklify-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: mongodb://mongo:27017/tasklify
            - name: PORT
              value: "5000"
